"""add submission dashboard index

Revision ID: 020da9e4787d
Revises: af57f6b4d3ee
Create Date: 2026-09-22 17:26:37.187610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020da9e4787d'
down_revision: Union[str, Sequence[str], None] = 'af57f6b4d3ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_submissions_widget_created', 'submissions', ['widget_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submissions_widget_created', table_name='submissions')
    # ### end Alembic commands ###
