"""add submission idempotency

Revision ID: af57f6b4d3ee
Revises: e431af9c9a42
Create Date: 2026-09-21 19:22:19.145652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af57f6b4d3ee'
down_revision: Union[str, Sequence[str], None] = 'e431af9c9a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submissions",
        sa.Column(
            "idempotency_key",
            sa.String(length=100),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE submissions
        SET idempotency_key = 'legacy-' || id::text
        WHERE idempotency_key IS NULL
        """
    )

    op.alter_column(
        "submissions",
        "idempotency_key",
        nullable=False,
    )

    op.create_unique_constraint(
        "uq_submission_widget_idempotency",
        "submissions",
        ["widget_id", "idempotency_key"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'idempotency_key')
    # ### end Alembic commands ###
